export enum WorkflowName {
  WALLET_WITHDRAWAL = "WALLET_WITHDRAWAL",
  WALLET_DEPOSIT = "WALLET_DEPOSIT",
  WALLET_TRANSFER = "WALLET_TRANSFER",
  PAYROLL_DEPOSIT = "PAYROLL_DEPOSIT",
  PAYROLL_PROCESSING = "PAYROLL_PROCESSING",
  CARD_WITHDRAWAL = "CARD_WITHDRAWAL",
  CARD_REVERSAL = "CARD_REVERSAL",
  BULK_ADD_EMPLOYEES = "BULK_ADD_EMPLOYEES",
  CREDIT_ADJUSTMENT = "CREDIT_ADJUSTMENT",
  DEBIT_ADJUSTMENT = "DEBIT_ADJUSTMENT",
}
