export enum InternalWorkflowName {
  PAYROLL_DEPOSIT = "PAYROLL_DEPOSIT",
  PAYROLL_PROCESSING = "PAYROLL_PROCESSING",
  BULK_ADD_EMPLOYEES = "BULK_ADD_EMPLOYEES",
  CREDIT_ADJUSTMENT = "CREDIT_ADJUSTMENT",
  DEBIT_ADJUSTMENT = "DEBIT_ADJUSTMENT",
  CARD_WITHDRAWAL = "CARD_WITHDRAWAL",
  CARD_REVERSAL = "CARD_REVERSAL",
  CARD_CREDIT_ADJUSTMENT = "CARD_CREDIT_ADJUSTMENT",
  CARD_DEBIT_ADJUSTMENT = "CARD_DEBIT_ADJUSTMENT",
}

export enum ConsumerWorkflowName {
  WALLET_WITHDRAWAL = "WALLET_WITHDRAWAL",
  WALLET_DEPOSIT = "WALLET_DEPOSIT",
  WALLET_TRANSFER = "WALLET_TRANSFER",
}
