version: "3.8"

services:
  noba_server:
    container_name: noba_server
    restart: on-failure
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=e2e_test
    ports:
      - "8080:8080"
    command: sh /e2e_test/docker_entrypoint.sh