version: "3.8"

services:
  postgres_db:
    container_name: postgres-db
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=e2e_user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=Noba_E2E
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U e2e_user -d Noba_E2E'"]
      interval: 10s
      timeout: 5s
      retries: 5

  noba_server:
    container_name: noba_server
    restart: on-failure
    build:
      context: ../
      dockerfile: e2e_test/Dockerfile
    depends_on:
      - postgres_db
    # network_mode: host
    ports:
      - "8080:8080"
        # entrypoint: docker-entrypoint.sh
    command: sh /docker-entrypoint.sh
