version: "3.8"
services:
  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    command: postgres -c shared_buffers=500MB -c fsync=off
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U prisma -d test'"]
      interval: 10s
      timeout: 3s
      retries: 5

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - DATABASE_URL=postgresql://prisma:prisma@db:5432/test?connect_timeout=300
    command: yarn test:prisma-migrate
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    volumes:
      - ./src:/src

volumes:
  db:
    driver: local
