/* eslint-disable @typescript-eslint/no-var-requires */
// eslint-disable-next-line @typescript-eslint/no-var-requires
const CircularDependencyPlugin = require("circular-dependency-plugin");
const ESLintPlugin = require("eslint-webpack-plugin");
//TODO add hot module reload? https://docs.nestjs.com/recipes/hot-reload

const webpackPlugins = [
  new CircularDependencyPlugin({
    // `onDetected` is called for each module that is cyclical
    onDetected({ module: webpackModuleRecord, paths, compilation }) {
      // `paths` will be an Array of the relative module paths that make up the cycle
      // `module` will be the module record generated by webpack that caused the cycle
      compilation.errors.push(new Error(paths.join(" -> ")));
    },
    //include exclude paths etc. https://www.npmjs.com/package/circular-dependency-plugin
    failOnError: true,
    allowAsyncCycles: false,
    cwd: process.cwd(),
  }),
];

module.exports = {
  entry: "./src/main",
  plugins: webpackPlugins,
};
