import { Inject, Injectable } from "@nestjs/common";
import { Prisma } from "@prisma/client";
import { WINSTON_MODULE_PROVIDER } from "nest-winston";
import { PrismaService } from "../../../../infraproviders/PrismaService";
import { Logger } from "winston";
import { PomeloUser as PrismaPomeloUserModel } from "@prisma/client";
import { PomeloCard as PrismaPomeloCardModel } from "@prisma/client";
import {
  convertToDomainPomeloUser,
  PomeloUser,
  PomeloUserSaveRequest,
  validatePomeloUser,
  validateSavePomeloUserRequest,
} from "../domain/PomeloUser";
import { PomeloRepo } from "./pomelo.repo";
import { RepoErrorCode, RepoException } from "../../../../core/exception/repo.exception";
import {
  PomeloCard,
  convertToDomainPomeloCard,
  PomeloCardSaveRequest,
  PomeloCardUpdateRequest,
  validatePomeloCard,
  validateSavePomeloCardRequest,
  validateUpdatePomeloCardRequest,
} from "../domain/PomeloCard";

@Injectable()
export class SqlPomeloRepo implements PomeloRepo {
  constructor(
    private readonly prismaService: PrismaService,
    @Inject(WINSTON_MODULE_PROVIDER) private readonly logger: Logger,
  ) {}

  async createPomeloUser(request: PomeloUserSaveRequest): Promise<PomeloUser> {
    validateSavePomeloUserRequest(request);

    let savedPomeloUser: PomeloUser = null;

    try {
      // Note that "createdTimestamp", "updatedTimestamp" & "ID" are not included in the input.
      // They are automatically generated by the database.
      const pomeloUserInput: Prisma.PomeloUserCreateInput = {
        consumer: {
          connect: {
            id: request.consumerID,
          },
        },
        pomeloID: request.pomeloUserID,
      };

      const returnedPomeloUser: PrismaPomeloUserModel = await this.prismaService.pomeloUser.create({
        data: pomeloUserInput,
      });
      savedPomeloUser = convertToDomainPomeloUser(returnedPomeloUser);
    } catch (err) {
      this.logger.error(JSON.stringify(err));
      throw new RepoException({
        errorCode: RepoErrorCode.DATABASE_INTERNAL_ERROR,
        message: "Error saving transaction in database",
      });
    }

    try {
      validatePomeloUser(savedPomeloUser);
      return savedPomeloUser;
    } catch (err) {
      this.logger.error(JSON.stringify(err));
      throw new RepoException({
        errorCode: RepoErrorCode.INVALID_DATABASE_RECORD,
        message: "Invalid database record",
      });
    }
  }

  async getPomeloUserByConsumerID(consumerID: string): Promise<PomeloUser> {
    try {
      const returnedPomeloUser: PrismaPomeloUserModel = await this.prismaService.pomeloUser.findUnique({
        where: {
          consumerID: consumerID,
        },
      });

      if (!returnedPomeloUser) {
        return null;
      }

      return convertToDomainPomeloUser(returnedPomeloUser);
    } catch (err) {
      this.logger.error(JSON.stringify(err));
      throw new RepoException({
        errorCode: RepoErrorCode.DATABASE_INTERNAL_ERROR,
        message: `Error getting the Pomelo user with consumerID: '${consumerID}'`,
      });
    }
  }

  async getPomeloUserByPomeloID(pomeloUserID: string): Promise<PomeloUser> {
    try {
      const returnedPomeloUser: PrismaPomeloUserModel = await this.prismaService.pomeloUser.findUnique({
        where: {
          pomeloID: pomeloUserID,
        },
      });

      if (!returnedPomeloUser) {
        return null;
      }

      return convertToDomainPomeloUser(returnedPomeloUser);
    } catch (err) {
      this.logger.error(JSON.stringify(err));
      throw new RepoException({
        errorCode: RepoErrorCode.DATABASE_INTERNAL_ERROR,
        message: `Error getting the Pomelo user with pomeloUserID: '${pomeloUserID}'`,
      });
    }
  }

  async createPomeloCard(request: PomeloCardSaveRequest): Promise<PomeloCard> {
    validateSavePomeloCardRequest(request);

    let savedPomeloCard: PomeloCard = null;

    try {
      // Note that "createdTimestamp", "updatedTimestamp" & "ID" are not included in the input.
      // They are automatically generated by the database.
      const pomeloCardInput: Prisma.PomeloCardCreateInput = {
        consumer: {
          connect: {
            id: request.nobaConsumerID,
          },
        },
        pomeloID: request.pomeloCardID,
        status: request.status,
        type: request.type,
      };

      const returnedPomeloCard: PrismaPomeloCardModel = await this.prismaService.pomeloCard.create({
        data: pomeloCardInput,
      });
      savedPomeloCard = convertToDomainPomeloCard(returnedPomeloCard);
    } catch (err) {
      this.logger.error(JSON.stringify(err));
      throw new RepoException({
        errorCode: RepoErrorCode.DATABASE_INTERNAL_ERROR,
        message: "Error saving transaction in database",
      });
    }

    try {
      validatePomeloCard(savedPomeloCard);
      return savedPomeloCard;
    } catch (err) {
      this.logger.error(JSON.stringify(err));
      throw new RepoException({
        errorCode: RepoErrorCode.INVALID_DATABASE_RECORD,
        message: "Invalid database record",
      });
    }
  }

  async updatePomeloCard(request: PomeloCardUpdateRequest): Promise<PomeloCard> {
    validateUpdatePomeloCardRequest(request);

    try {
      const pomeloCardUpdate: Prisma.PomeloCardUpdateInput = {
        status: request.status,
      };

      const returnedPomeloCard: PrismaPomeloCardModel = await this.prismaService.pomeloCard.update({
        where: {
          nobaConsumerID_pomeloID: {
            nobaConsumerID: request.nobaConsumerID,
            pomeloID: request.pomeloCardID,
          },
        },
        data: pomeloCardUpdate,
      });

      return convertToDomainPomeloCard(returnedPomeloCard);
    } catch (err) {
      this.logger.error(JSON.stringify(err));
      if (err.meta && err.meta.cause === "Record to update not found.") {
        throw new RepoException({
          errorCode: RepoErrorCode.NOT_FOUND,
          message: `Pomelo Card with (consumerID, pomeloCardID): '(${request.nobaConsumerID}, ${request.pomeloCardID})' was not found.`,
        });
      }
      throw new RepoException({
        errorCode: RepoErrorCode.DATABASE_INTERNAL_ERROR,
        message: "Error updating record in database",
      });
    }
  }

  async getPomeloCard(consumerID: string, pomeloCardID: string): Promise<PomeloCard> {
    try {
      const returnedPomeloCard: PrismaPomeloCardModel = await this.prismaService.pomeloCard.findUnique({
        where: {
          nobaConsumerID_pomeloID: {
            nobaConsumerID: consumerID,
            pomeloID: pomeloCardID,
          },
        },
      });

      if (!returnedPomeloCard) {
        return null;
      }

      return convertToDomainPomeloCard(returnedPomeloCard);
    } catch (err) {
      this.logger.error(JSON.stringify(err));
      throw new RepoException({
        errorCode: RepoErrorCode.DATABASE_INTERNAL_ERROR,
        message: `Error getting the Pomelo Card with (consumerID, pomeloCardID): '(${consumerID}, ${pomeloCardID})'`,
      });
    }
  }

  async getPomeloCardByID(id: string): Promise<PomeloCard> {
    try {
      const returnedPomeloCard: PrismaPomeloCardModel = await this.prismaService.pomeloCard.findUnique({
        where: {
          id: id,
        },
      });

      if (!returnedPomeloCard) {
        return null;
      }

      return convertToDomainPomeloCard(returnedPomeloCard);
    } catch (err) {
      this.logger.error(JSON.stringify(err));
      throw new RepoException({
        errorCode: RepoErrorCode.DATABASE_INTERNAL_ERROR,
        message: `Error getting the Pomelo Card with ID: '${id}'`,
      });
    }
  }
}
