export enum TransactionType {
  ONRAMP = "onramp",
  OFFRAMP = "offramp",
  SWAP = "swap",
}

export enum TransactionStatus {
  INITIATED = "INITIATED",

  FIAT_INCOMING_PENDING = "FIAT_INCOMING_PENDING",
  FIAT_INCOMING_CONFIRMED = "FIAT_INCOMING_CONFIRMED",
  FIAT_INCOMING_FAILED = "FIAT_INCOMING_FAILED",
  FIAT_INCOMING_REVERSED = "FIAT_INCOMING_REVERSED",
  FIAT_OUTGOING_PENDING = "FIAT_OUTGOING_PENDING",
  FIAT_OUTGOING_CONFIRMED = "FIAT_OUTGOING_CONFIRMED",
  FIAT_OUTGOING_FAILED = "FIAT_OUTGOING_FAILED",

  WALLET_INCOMING_PENDING = "WALLET_INCOMING_PENDING",
  WALLET_INCOMING_COMPLETED = "WALLET_INCOMING_COMPLETED",
  WALLET_INCOMING_FAILED = "WALLET_INCOMING_FAILED",
  WALLET_OUTGOING_PENDING = "WALLET_OUTGOING_PENDING",
  WALLET_OUTGOING_COMPLETED = "WALLET_OUTGOING_COMPLETED",
  WALLET_OUTGOING_FAILED = "WALLET_OUTGOING_FAILED",

  COMPLETED = "COMPLETED",
}
