import {
  CHECKOUT_AWS_SECRET_NAME_FOR_CHECKOUT_PUBLIC_KEY as CHECKOUT_AWS_SECRET_NAME_FOR_PUBLIC_KEY,
  CHECKOUT_AWS_SECRET_NAME_FOR_CHECKOUT_SECRET_KEY as CHECKOUT_AWS_SECRET_NAME_FOR_SECRET_KEY,
  CHECKOUT_PUBLIC_KEY,
  CHECKOUT_SECRET_KEY,
} from "../ConfigurationUtils";

export interface CheckoutConfigs {
  [CHECKOUT_PUBLIC_KEY]: string;
  [CHECKOUT_SECRET_KEY]: string;
  [CHECKOUT_AWS_SECRET_NAME_FOR_PUBLIC_KEY]: string;
  [CHECKOUT_AWS_SECRET_NAME_FOR_SECRET_KEY]: string;
}
