import {
  CHECKOUT_AWS_SECRET_NAME_FOR_CHECKOUT_PUBLIC_KEY as CHECKOUT_AWS_SECRET_NAME_FOR_PUBLIC_KEY,
  CHECKOUT_AWS_SECRET_NAME_FOR_CHECKOUT_SECRET_KEY as CHECKOUT_AWS_SECRET_NAME_FOR_SECRET_KEY,
  CHECKOUT_COUPON_CODE,
  CHECKOUT_PARTNER_ID,
  CHECKOUT_PROCESSING_CHANNEL_ID,
  CHECKOUT_PUBLIC_KEY,
  CHECKOUT_SECRET_KEY,
} from "../ConfigurationUtils";

export interface CheckoutConfigs {
  [CHECKOUT_PUBLIC_KEY]: string;
  [CHECKOUT_SECRET_KEY]: string;
  [CHECKOUT_AWS_SECRET_NAME_FOR_PUBLIC_KEY]: string;
  [CHECKOUT_AWS_SECRET_NAME_FOR_SECRET_KEY]: string;
  [CHECKOUT_COUPON_CODE]: string;
  [CHECKOUT_PARTNER_ID]: number;
  [CHECKOUT_PROCESSING_CHANNEL_ID]: string;
}
