import {
  MONO_AWS_SECRET_KEY_FOR_BASE_URL,
  MONO_AWS_SECRET_KEY_FOR_BEARER_TOKEN,
  MONO_AWS_SECRET_KEY_FOR_NOBA_ACCOUNT_ID,
  MONO_AWS_SECRET_KEY_FOR_WEBHOOK_SECRET,
  MONO_NOBA_PAYROLL_ACCOUNT_NUMBER,
  MONO_BASE_URL,
  MONO_BEARER_TOKEN,
  MONO_NOBA_ACCOUNT_ID,
  MONO_WEBHOOK_SECRET,
  MONO_AWS_SECRET_KEY_FOR_NOBA_PAYROLL_ACCOUNT_NUMBER,
} from "../ConfigurationUtils";

export interface MonoConfigs {
  [MONO_BASE_URL]: string;
  [MONO_BEARER_TOKEN]: string;
  [MONO_NOBA_ACCOUNT_ID]: string;
  [MONO_NOBA_PAYROLL_ACCOUNT_NUMBER]: string;
  [MONO_WEBHOOK_SECRET]: string;
  [MONO_AWS_SECRET_KEY_FOR_BASE_URL]: string;
  [MONO_AWS_SECRET_KEY_FOR_BEARER_TOKEN]: string;
  [MONO_AWS_SECRET_KEY_FOR_NOBA_ACCOUNT_ID]: string;
  [MONO_AWS_SECRET_KEY_FOR_NOBA_PAYROLL_ACCOUNT_NUMBER]: string;
  [MONO_AWS_SECRET_KEY_FOR_WEBHOOK_SECRET]: string;
}
