import { MONO_AWS_SECRET_KEY_FOR_BASE_URL, MONO_AWS_SECRET_KEY_FOR_BEARER_TOKEN, MONO_AWS_SECRET_KEY_FOR_NOBA_ACCOUNT_ID, MONO_BASE_URL, MONO_BEARER_TOKEN, MONO_NOBA_ACCOUNT_ID } from "../ConfigurationUtils";

export interface MonoConfigs {
  [MONO_BASE_URL]: string;
  [MONO_BEARER_TOKEN]: string;
  [MONO_NOBA_ACCOUNT_ID]: string;
  [MONO_AWS_SECRET_KEY_FOR_BASE_URL]: string;
  [MONO_AWS_SECRET_KEY_FOR_BEARER_TOKEN]: string;
  [MONO_AWS_SECRET_KEY_FOR_NOBA_ACCOUNT_ID]: string;
}

