import {
  NOBA_WORKFLOW_AWS_SECRET_KEY_FOR_CLIENT_URL,
  NOBA_WORKFLOW_AWS_SECRET_KEY_FOR_TASK_QUEUE,
  NOBA_WORKFLOW_CLIENT_URL,
  NOBA_WORKFLOW_CONNECTION_TIMEOUT_IN_MILLIS,
  NOBA_WORKFLOW_NAMESPACE,
  NOBA_WORKFLOW_TASK_QUEUE,
  NOBA_WORKFLOW_TEMPORAL_CLOUD_CERTIFICATE,
  NOBA_WORKFLOW_TEMPORAL_CLOUD_PRIVATE_KEY,
  NOBA_WORKFLOW_AWS_SECRET_KEY_FOR_TEMPORAL_CLOUD_CERTIFICATE,
  NOBA_WORKFLOW_AWS_SECRET_KEY_FOR_TEMPORAL_CLOUD_PRIVATE_KEY,
  NOBA_PAYROLL_ACCOUNT_NUMBER,
  NOBA_PAYROLL_AWS_SECRET_KEY_FOR_NOBA_PAYROLL_ACCOUNT_NUMBER,
} from "../ConfigurationUtils";

export interface NobaWorkflowConfig {
  [NOBA_WORKFLOW_TASK_QUEUE]: string;
  [NOBA_WORKFLOW_AWS_SECRET_KEY_FOR_TASK_QUEUE]: string;
  [NOBA_WORKFLOW_CLIENT_URL]: string;
  [NOBA_WORKFLOW_AWS_SECRET_KEY_FOR_CLIENT_URL]: string;
  [NOBA_WORKFLOW_NAMESPACE]: string;
  [NOBA_WORKFLOW_CONNECTION_TIMEOUT_IN_MILLIS]: number;
  [NOBA_WORKFLOW_TEMPORAL_CLOUD_CERTIFICATE]: string;
  [NOBA_WORKFLOW_TEMPORAL_CLOUD_PRIVATE_KEY]: string;
  [NOBA_WORKFLOW_AWS_SECRET_KEY_FOR_TEMPORAL_CLOUD_CERTIFICATE]: string;
  [NOBA_WORKFLOW_AWS_SECRET_KEY_FOR_TEMPORAL_CLOUD_PRIVATE_KEY]: string;
  [NOBA_PAYROLL_ACCOUNT_NUMBER]: string;
  [NOBA_PAYROLL_AWS_SECRET_KEY_FOR_NOBA_PAYROLL_ACCOUNT_NUMBER]: string;
}
