import {
  NOBA_WORKFLOW_AWS_SECRET_KEY_FOR_CLIENT_URL,
  NOBA_WORKFLOW_AWS_SECRET_KEY_FOR_TASK_QUEUE,
  NOBA_WORKFLOW_CLIENT_URL,
  NOBA_WORKFLOW_CONNECTION_TIMEOUT_IN_MILLIS,
  NOBA_WORKFLOW_NAMESPACE,
  NOBA_WORKFLOW_TASK_QUEUE,
} from "../ConfigurationUtils";

export interface NobaWorkflowConfig {
  [NOBA_WORKFLOW_TASK_QUEUE]: string;
  [NOBA_WORKFLOW_AWS_SECRET_KEY_FOR_TASK_QUEUE]: string;
  [NOBA_WORKFLOW_CLIENT_URL]: string;
  [NOBA_WORKFLOW_AWS_SECRET_KEY_FOR_CLIENT_URL]: string;
  [NOBA_WORKFLOW_NAMESPACE]: string;
  [NOBA_WORKFLOW_CONNECTION_TIMEOUT_IN_MILLIS]: number;
}

export enum NobaWorkflowNames {
  DEBIT_CONSUMER_WALLET = "DebitConsumerWallet",
}
