import {
  POMELO_AFFINITY_GROUP,
  POMELO_API_BASE_URL,
  POMELO_AUDIENCE,
  POMELO_AUTH_BASE_URL,
  POMELO_AWS_SECRET_KEY_FOR_AFFINITY_GROUP,
  POMELO_AWS_SECRET_KEY_FOR_CLIENT_ID,
  POMELO_AWS_SECRET_KEY_FOR_CLIENT_SECRET,
  POMELO_CLIENT_ID,
  POMELO_CLIENT_SECRET,
} from "../ConfigurationUtils";

export interface PomeloConfigs {
  [POMELO_CLIENT_ID]: string;
  [POMELO_CLIENT_SECRET]: string;
  [POMELO_AWS_SECRET_KEY_FOR_CLIENT_ID]: string;
  [POMELO_AWS_SECRET_KEY_FOR_CLIENT_SECRET]: string;
  [POMELO_AFFINITY_GROUP]: string;
  [POMELO_AWS_SECRET_KEY_FOR_AFFINITY_GROUP]: string;
  [POMELO_AUTH_BASE_URL]: string;
  [POMELO_API_BASE_URL]: string;
  [POMELO_AUDIENCE]: string;
}
