import {
  SQUID_API_KEY,
  SQUID_AWS_SECRET_NAME_FOR_API_KEY_ATTR,
  SQUID_BASE_URL,
  SQUID_INTERMEDIARY_LEG,
  SQUID_SLIPPAGE,
  SQUID_TEMPORARY_WALLET_ADDRESS,
} from "../ConfigurationUtils";

export interface SquidConfigs {
  [SQUID_API_KEY]: string;
  [SQUID_AWS_SECRET_NAME_FOR_API_KEY_ATTR]: string;
  [SQUID_BASE_URL]: string;
  [SQUID_INTERMEDIARY_LEG]: string;
  [SQUID_TEMPORARY_WALLET_ADDRESS]: string;
  [SQUID_SLIPPAGE]: number;
}
