import {
  ZEROHASH_API_KEY,
  ZEROHASH_API_SECRET,
  ZEROHASH_AWS_SECRET_KEY_FOR_API_KEY_ATTR,
  ZEROHASH_AWS_SECRET_KEY_FOR_API_SECRET_ATTR,
  ZEROHASH_AWS_SECRET_KEY_FOR_HOST_ATTR,
  ZEROHASH_AWS_SECRET_KEY_FOR_PASS_PHRASE_ATTR,
  ZEROHASH_HOST,
  ZEROHASH_PASS_PHRASE,
  ZEROHASH_PLATFORM_CODE,
  ZEROHASH_AWS_SECRET_KEY_FOR_PLATFORM_CODE,
  ZEROHASH_PROXY_SERVER_IP,
  ZEROHASH_PROXY_SERVER_PORT,
} from "../ConfigurationUtils";

export interface ZerohashConfigs {
  [ZEROHASH_API_KEY]: string;
  [ZEROHASH_API_SECRET]: string;
  [ZEROHASH_PASS_PHRASE]: string;
  [ZEROHASH_HOST]: string;
  [ZEROHASH_AWS_SECRET_KEY_FOR_API_KEY_ATTR]: string;
  [ZEROHASH_AWS_SECRET_KEY_FOR_API_SECRET_ATTR]: string;
  [ZEROHASH_AWS_SECRET_KEY_FOR_PASS_PHRASE_ATTR]: string;
  [ZEROHASH_AWS_SECRET_KEY_FOR_HOST_ATTR]: string;
  [ZEROHASH_PLATFORM_CODE]: string;
  [ZEROHASH_AWS_SECRET_KEY_FOR_PLATFORM_CODE]: string;
  [ZEROHASH_PROXY_SERVER_IP]: string;
  [ZEROHASH_PROXY_SERVER_PORT]: number;
}

export const ZHLS_PLATFORM_CODE = "00SCXM";
