envType: "production"

# ***** SENSITIVE PRODUCTION CONFIGURATIONS SUCH AS PASSWORDS,SECRETS SHOULDN'T BE PUT HERE,
# ***** INSTEAD SHOULD BE INJECTED FROM SECRETS AT RUNTIME OR SHOULD BE PASSED AS ENVIRONMENT VARIABLE

apiPrefix: "/v1"
logFilePath: "/home/ubuntu/noba_server.log"

awsRegion: "us-east-1"
awsDefaultRegion: "us-east-1"
awsAccountID: "210194402305"

kms:
  context:
    stage: "production"
    purpose: "Noba Onramp app"
    origin: "us-east-1"
  ssn:
    awsSecretNameForGeneratorKeyArn: "PROD_SSN_GENERATOR_KEY_ARN"
    generatorKeyArn: "bogus-value"
    awsSecretNameForFollowUpKeyArn: "PROD_SSN_FOLLOW_UP_KEY_1_ARN"
    followUpKeyArn: "bogus-value"

# AWS KMS Encryption key references
# kmsGeneratorKeyID is global to all keys
# Each key followed by _keyID uses a prefix which is our alias to that key. This must match between KMS and our application.
awskms:
  kmsGeneratorKeyID: "arn:aws:kms:us-east-1:210194402305:alias/master-key"
  ssn-encryption-key_keyID: "arn:aws:kms:us-east-1:210194402305:key/39d511f4-c1ff-4d21-b6d5-c3347f0b671c"

#in production we should take it from vault, only for testing here, todo remove or create test api_key with limit on number of emails
sendgrid:
  awsSecretNameForApiKey: "PROD_SENDGRID_SECRET" # if this is present then we fetch the secret key from aws secret manager else we take it from the configs, for production environment we shouldn't put the secret in the config files
  apiKey: "bogus-value"

stripe:
  awsSecretNameForSecretKey: "PROD_STRIPE_SECRET" # if this is present then we fetch the secret key from aws secret manager else we take it from the configs, for production environment we shouldn't put the secret in the config files
  secretKey: "bogus-value"

twilio:
  awsSecretNameForSID: "PROD_TWILIO_SID"
  awsSecretNameForAuthToken: "PROD_TWILIO_SECRET"
  SID: "bogus-value"
  authToken: "bogus-value"
  fromPhoneNumber: "+19894557345"

mongo:
  awsSecretNameForUri: "PROD_DOCUMENT_DB_URI"
  uri: "bogus-value"
  sslEnabled: true
  sslCAPath: rds-combined-ca-bundle.pem #bootstrapped in deploy scripts

sardine:
  awsSecretNameForSardineClientID: "PROD_SARDINE_CLIENT_ID" # if this is present then we fetch the secret key from aws secret manager else we take it from the configs, for production environment we shouldn't put the secret in the config files
  awsSecretNameForSardineSecretKey: "PROD_SARDINE_SECRET"
  clientID: "bogus-value"
  secretKey: "bogus-value"
  sardineBaseUri: "https://api.sardine.ai"

noba:
  partnerID: "d4KZqfVKwSHWueOJhmgN-"
  transaction:
    spreadPercentage: ""
    awsSecretKeyForSpreadPercentage: "PROD_NOBA_SPREAD_PERCENTAGE"
    flatFeeDollars: ""
    awsSecretKeyForFlatFeeDollars: "PROD_NOBA_FLAT_FEE_DOLLARS"
    dynamicCreditCardFeePercentage: ""
    awsSecretKeyForDynamicCreditCardFeePercentage: "PROD_NOBA_DYNAMIC_CREDIT_CARD_FEE_PERCENTAGE"
    fixedCreditCardFee: ""
    awsSecretKeyForFixedCreditCardFee: "PROD_NOBA_FIXED_CREDIT_CARD_FEE_DOLLARS"

zerohash:
  awsSecretNameforApiKey: "PROD_ZEROHASH_API_KEY" # if this is present then we fetch the secret key from aws secret manager else we take it from the configs, for production environment we shouldn't put the secret in the config files
  awsSecretNameForApiSecret: "PROD_ZEROHASH_API_SECRET" # if this is present then we fetch the secret key from aws secret manager else we take it from the configs, for production environment we shouldn't put the secret in the config files
  awsSecretNameForPassPhrase: "PROD_ZEROHASH_PASS_PHRASE" # if this is present then we fetch the secret key from aws secret manager else we take it from the configs, for production environment we shouldn't put the secret in the config files
  awsSecretNameForHost: "PROD_ZEROHASH_HOST"
  apiKey: ""
  apiSecret: ""
  passPhrase: ""
  host: ""

configuration:
  lowAmountThreshold: 50
  highAmountThreshold: 200
  cryptoImageBaseUrl: "https://dj61eezhizi5l.cloudfront.net/assets/images/currency-logos/crypto"
  fiatImageBaseUrl: "https://dj61eezhizi5l.cloudfront.net/assets/images/currency-logos/fiat"

supportedCryptoFileName: "supported_tokens.csv"
locationDataFileName: "countries+states.json"
