envType: "staging"

# ***** SENSITIVE PRODUCTION CONFIGURATIONS SUCH AS PASSWORDS,SECRETS SHOULDN'T BE PUT HERE,
# ***** INSTEAD SHOULD BE INJECTED FROM SECRETS AT RUNTIME OR SHOULD BE PASSED AS ENVIRONMENT VARIABLE

apiPrefix: "/v1"
logFilePath: "noba_server.log"

awsRegion: "us-east-1"
awsDefaultRegion: "us-east-1"
awsAccountID: "210194402305"

kms:
  context:
    stage: "development"
    purpose: "Noba Onramp app"
    origin: "us-east-1"
  ssn:
    awsSecretNameForGeneratorKeyArn: "TEST_SSN_GENERATOR_KEY_ARN"
    generatorKeyArn: "bogus-value"
    awsSecretNameForFollowUpKeyArn: "TEST_SSN_FOLLOW_UP_KEY_1_ARN"
    followUpKeyArn: "bogus-value"

#in production we should take it from vault, only for testing here, todo remove or create test api_key with limit on number of emails
sendgrid:
  awsSecretNameForApiKey: "TEST_SENDGRID_SECRET" #if this is present then we fetch the secret key from aws secret manager else we take it from the configs, for production environment we shouldn't put the secret in the config files
  apiKey: "bogus-value"

checkout:
  awsSecretNameForPublicKey: "TEST_CHECKOUT_PUBLIC_KEY" # if this is present then we fetch the secret key from aws secret manager else we take it from the configs, for production environment we shouldn't put the secret in the config files
  awsSecretNameForSecretKey: "TEST_CHECKOUT_SECRET_KEY"
  publicKey: "bogus-value"
  secretKey: "bogus-value"
  couponCode: "NY2018"
  partnerId: 123989

twilio:
  awsSecretNameForSID: ""
  awsSecretNameForAuthToken: ""
  SID: "AC4efa22156849ec40b383a80f45525409"
  authToken: "c34165debbb0a77e3507884e86b88772"
  fromPhoneNumber: "+19894557345"

mongo:
  awsSecretNameForUri: "STAGING_DOCUMENT_DB_URI"
  uri: "bogus-value"
  sslEnabled: true
  sslCAPath: rds-combined-ca-bundle.pem # bootstrapped in deploy scripts

sardine:
  awsSecretNameForSardineClientID: "TEST_SARDINE_CLIENT_ID" # if this is present then we fetch the secret key from aws secret manager else we take it from the configs, for production environment we shouldn't put the secret in the config files
  awsSecretNameForSardineSecretKey: "TEST_SARDINE_SECRET"
  awsSecretNameForSardineWebhookSecretKey: "TEST_SARDINE_WEBHOOK_SECRET"
  clientID: "bogus-value"
  secretKey: "bogus-value"
  webhookSecretKey: "bogus-value"
  sardineBaseUri: "https://api.sandbox.sardine.ai"

noba:
  partnerID: "2WZta9esGVKLfdWWcApYC"
  apiKeyForEmbed: "Noba-Partner-qENyQjz7mMENVIa_-VcL_"
  transaction:
    spreadPercentage: ""
    awsSecretKeyForSpreadPercentage: "TEST_NOBA_SPREAD_PERCENTAGE"
    flatFeeDollars: ""
    awsSecretKeyForFlatFeeDollars: "TEST_NOBA_FLAT_FEE_DOLLARS"
    dynamicCreditCardFeePercentage: ""
    awsSecretKeyForDynamicCreditCardFeePercentage: "TEST_NOBA_DYNAMIC_CREDIT_CARD_FEE_PERCENTAGE"
    fixedCreditCardFee: ""
    awsSecretKeyForFixedCreditCardFee: "TEST_NOBA_FIXED_CREDIT_CARD_FEE_DOLLARS"
    slippageAllowedPercentage: ""
    awsSecretKeyForSlippageAllowedPercentage: "TEST_NOBA_SLIPPAGE_ALLOWED_PERCENTAGE"

zerohash:
  awsSecretNameForApiKey: "TEST_ZEROHASH_API_KEY" # if this is present then we fetch the secret key from aws secret manager else we take it from the configs, for production environment we shouldn't put the secret in the config files
  awsSecretNameForApiSecret: "TEST_ZEROHASH_API_SECRET" # if this is present then we fetch the secret key from aws secret manager else we take it from the configs, for production environment we shouldn't put the secret in the config files
  awsSecretNameForPassPhrase: "TEST_ZEROHASH_PASS_PHRASE" # if this is present then we fetch the secret key from aws secret manager else we take it from the configs, for production environment we shouldn't put the secret in the config files
  awsSecretNameForHost: "TEST_ZEROHASH_HOST"
  awsSecretNameForPlatformCode: "TEST_ZEROHASH_PLATFORM_CODE"
  apiKey: ""
  apiSecret: ""
  passPhrase: ""
  host: ""
  platformCode: ""
  proxyServerIP: "172.31.8.170"
  proxyServerPort: 3128

elliptic:
  awsSecretNameForApiKey: "TEST_ELLIPTIC_KEY"
  awsSecretNameForSecretKey: "TEST_ELLIPTIC_SECRET"
  apiKey: ""
  secretKey: ""
  baseUrl: "https://aml-api.elliptic.co"

squid:
  awsSecretNameForApiKey: "TEST_SQUID_API_KEY"
  apiKey: ""
  baseUrl: "https://testnet.api.0xsquid.com"
  intermediaryLeg: "AVAX"
  temporaryWalletAddress: "0xDb933AE704a2D8acF4201D75106464b30dEC1E4e"
  slippage: 1

configuration:
  lowAmountThreshold: .01
  highAmountThreshold: 200
  cryptoImageBaseUrl: "https://dj61eezhizi5l.cloudfront.net/assets/images/currency-logos/crypto"
  fiatImageBaseUrl: "https://dj61eezhizi5l.cloudfront.net/assets/images/currency-logos/fiat"

partner:
  embedSecretKey: "Noba_Secret_1660579071114_kP7KBfORrDVWmUsCcuBOX"

plaid:
  env: "development"
  version: "2020-09-14"
  redirectUri: ""
  awsSecretNameForRedirectUri: "TEST_PLAID_REDIRECT_URI"
  clientID: ""
  awsSecretNameForClientID: "TEST_PLAID_CLIENT_ID"
  secretKey: ""
  awsSecretNameForSecretKey: "TEST_PLAID_SECRET_KEY"

locationDataFileName: "countries+states.json"
ccBINDataFileNameMask: "all_bins.csv"
assetsBucketName: "prod-noba-assets"
supportedCryptoFileBucketPath: "assets/data/cryptocurrency_tokens.csv"
sanctionedCryptoWalletsFileBucketPath: "assets/data/sanctioned_wallets.csv"
