name: Link PR to Jira Issue
on:
  pull_request:
    types: [opened]

# This action adapted from https://dev.fandom.com/wiki/User_blog:Ritaly-dev/Auto_linking_Jira_ticket_in_PR_description_via_Github_Action

jobs:
  update_pr:
    name: Link PR to Jira Issue
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch
        id: check-branch
        run: |
          if [[ ${{ github.head_ref }} =~ ^[A-Za-z]+-[0-9]+.*$ ]]; then
              echo "match=true" >> $GITHUB_OUTPUT
          fi
      - uses: tzkhan/pr-update-action@v2
        if: steps.check-branch.outputs.match == 'true'
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: '[A-Za-z\d-_.\\/]+'
          head-branch-regex: '^([A-Za-z])+-\d+'
          title-template: '[%headbranch%] '
          body-template: |
            Jira issue: [%headbranch%](https://noba.atlassian.net/browse/%headbranch%)
            ---
          body-update-action: 'prefix'
          body-uppercase-base-match: false