name: Main Workflow

on:
  # Run whenever a PR that targets main is created or updated
  pull_request:
    branches: [main]

  # Run whenever we push to main
  push:
    branches: [main]

  # Allow running manually from GitHub
  workflow_dispatch:

permissions:
  checks: write
  contents: write

jobs:
  setup-environment:
    uses: nobapay/NobaServer/.github/workflows/setup-environment.yml@fix-failing-linters

  run-linters:
    uses: nobapay/NobaServer/.github/workflows/run-linters.yml@fix-failing-linters
    secrets: inherit
    permissions:
      checks: write
      contents: write
    needs: [setup-environment]

  run-unit-tests:
    uses: nobapay/NobaServer/.github/workflows/run-unit-tests.yml@fix-failing-linters
    secrets: inherit
    needs: [setup-environment]

  run-e2e-tests:
    uses: nobapay/NobaServer/.github/workflows/run-e2e-tests.yml@fix-failing-linters
    secrets: inherit
    needs: [setup-environment]

  sonarcloud-scan:
    uses: nobapay/NobaServer/.github/workflows/run-sonar-scan.yml@fix-failing-linters
    secrets: inherit
    needs: [setup-environment, run-unit-tests]
