name: Main Workflow

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  # Run whenever a PR that targets main is created or updated
  pull_request:
    branches: [main]

  # Run whenever we push to main
  push:
    branches: [main]

  # Allow running manually from GitHub
  workflow_dispatch:

jobs:
  setup-environment:
    uses: ./.github/workflows/setup-environment.yml

  run-linters:
    uses: ./.github/workflows/run-linters.yml
    secrets: inherit
    needs: [setup-environment]

  run-unit-tests:
    uses: ./.github/workflows/run-unit-tests.yml
    secrets: inherit
    needs: [setup-environment]

  run-unit-tests2:
    uses: ./.github/workflows/run-unit-tests2.yml
    secrets: inherit
    needs: [setup-environment]

  run-integration-tests:
    uses: ./.github/workflows/run-integration-tests.yml
    secrets: inherit
    needs: [setup-environment]

  sonarcloud-scan:
    uses: ./.github/workflows/run-sonar-scan.yml
    secrets: inherit
    needs: [setup-environment, run-unit-tests, run-unit-tests2]
