name: Pull Request Workflow

on:
  # Run whenever a PR that targets main is created or updated
  pull_request:
    branches: main

  # Allow running manually from GitHub
  workflow_dispatch:

jobs:
  setup-environment:
    uses: nobapay/NobaServer/.github/workflows/setup-environment.yml

  run-linters:
    uses: nobapay/NobaServer/.github/workflows/run-linters.yml
    needs: [setup-environment]

  run-unit-tests:
    uses: nobapay/NobaServer/.github/workflows/run-unit-tests.yml
    secrets: inherit
    needs: [setup-environment]

  run-e2e-tests:
    uses: nobapay/NobaServer/.github/workflows/run-e2e-tests.yml
    secrets: inherit
    needs: [setup-environment]

  sonarcloud-scan:
    uses: nobapay/NobaServer/.github/workflows/run-sonar-scan.yml
    secrets: inherit
    needs: [setup-environment, run-unit-tests]
