name: SonarCloud Update

on:
  # Run whenever we push to main
  push:
    branches: main

  # Allow running manually from GitHub
  workflow_dispatch:

jobs:
  setup-environment:
    uses: nobapay/NobaServer/.github/workflows/setup-environment.yml

  run-unit-tests:
    uses: nobapay/NobaServer/.github/workflows/run-unit-tests.yml
    secrets: inherit
    needs: [setup-environment]

  sonarcloud-scan:
    uses: nobapay/NobaServer/.github/workflows/run-sonar-scan.yml
    secrets: inherit
    needs: [setup-environment, run-unit-tests]
