name: _Run Integration Tests

on:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  e2e_test:
    runs-on: ubuntu-latest
    name: Run Integration Tests
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub PostgreSQL image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: e2e_user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: Noba_E2E
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5456:5432

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Restore environment from cache
        id: restore-environment
        uses: actions/cache@v3
        env:
          cache-name: ${{ github.run_number }}
        with:
          path: ./
          key: ${{ runner.os }}-build-${{ github.run_number }}
      - name: Run db migrations
        env:
          DATABASE_URL: postgresql://e2e_user:pass@localhost:5456/Noba_E2E?connect_timeout=300
        run: yarn prisma-clean-init

      - name: Integration tests
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          AWS_DEFAULT_REGION: us-east-1
          DATABASE_URL: postgresql://e2e_user:pass@localhost:5456/Noba_E2E?connect_timeout=300
        run: yarn test:integration assets --silent=False
