name: _Run SonarCloud Scan
on:
  workflow_call:

jobs:
  sonarcloud-scan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Restore tests1 environment from cache
        id: restore-environment1
        uses: actions/cache@v3
        env:
          cache-name: ${{ github.run_number }}-tests1
        with:
          path: ./
          key: ${{ runner.os }}-build-${{ github.run_number }}-tests1

      - name: Restore tests2 environment from cache
        id: restore-environment2
        uses: actions/cache@v3
        env:
          cache-name: ${{ github.run_number }}-tests2
        with:
          path: ./
          key: ${{ runner.os }}-build-${{ github.run_number }}-tests2

      - name: Merge lcov files
        run: |
          ls -la
          yarn add lcov-result-merger
          yarn lcov-result-merger 'coverage-*/*.lcov' coverage_merged.lcov

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          coverageReportPaths: 'coverage_merged.lcov'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          BUILD_NUMBER: ${{ github.run_number }}

      # - name: SonarQube Quality Gate Check
      #   uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
