name: Run Linters

on:
  workflow_call:

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
          auto_fix: false
          eslint_auto_fix: false
          prettier_auto_fix: false
