name: _Run Unit Tests

on:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub PostgreSQL image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Restore environment from cache
        id: restore-environment
        uses: actions/cache@v3
        env:
          cache-name: ${{ github.run_number }}
        with:
          path: ./
          key: ${{ runner.os }}-build-${{ github.run_number }}

      - name: Run db migrations
        env:
            DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test?connect_timeout=300
        run: yarn prisma-update

      - name: Unit tests with coverage
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test?connect_timeout=300
        run: yarn test:unit

      - name: Cache test results
        id: cache-test-results
        uses: actions/cache@v3
        env:
          cache-name: ${{ github.run_number }}-tests
        with:
          path: ./
          key: ${{ runner.os }}-build-${{ github.run_number }}-tests