name: _Run Unit Tests

on:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Restore environment from cache
        id: restore-environment
        uses: actions/cache@v3
        env:
          cache-name: ${{ github.run_number }}
        with:
          path: ./
          key: ${{ runner.os }}-build-${{ github.run_number }}

      - name: Create .env file
        run: |
          touch .env
          echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} >> .env
          echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> .env
          echo DATABASE_URL=postgresql://prisma:prisma@db:5432/test?connect_timeout=300 >> .env
      - name: Unit tests with coverage
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: docker-compose -f docker-compose.test.yml up build --exit-code-from test

      - name: Cache test results
        id: cache-test-results
        uses: actions/cache@v3
        env:
          cache-name: ${{ github.run_number }}-tests
        with:
          path: ./
          key: ${{ runner.os }}-build-${{ github.run_number }}-tests