name: _Run SonarCloud Scan
on:
  workflow_call:

jobs:
  sonarcloud-scan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Restore repos tests environment from cache
        id: restore-environment-repos
        uses: actions/cache@v3
        env:
          cache-name: ${{ github.run_number }}-repos
        with:
          path: ./
          key: ${{ runner.os }}-build-${{ github.run_number }}-repos

      - name: Restore controllers tests environment from cache
        id: restore-environment-controllers
        uses: actions/cache@v3
        env:
          cache-name: ${{ github.run_number }}-controllers
        with:
          path: ./
          key: ${{ runner.os }}-build-${{ github.run_number }}-controllers

      - name: Restore controllers others environment from cache
        id: restore-environment-others
        uses: actions/cache@v3
        env:
          cache-name: ${{ github.run_number }}-others
        with:
          path: ./
          key: ${{ runner.os }}-build-${{ github.run_number }}-others

      - name: Clean up coverage reports
        run: |
          rm -rf src/coverage-*/lcov-report

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.javascript.lcov.reportPaths=src/coverage-*/lcov.info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          BUILD_NUMBER: ${{ github.run_number }}

      # - name: SonarQube Quality Gate Check
      #   uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
