name: _Run Linters

on:
  workflow_call:

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Restore environment from cache
        id: restore-environment
        uses: actions/cache@v3
        env:
          cache-name: ${{ github.run_number }}
        with:
          path: ./
          key: ${{ runner.os }}-build-${{ github.run_number }}

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
          auto_fix: false
          eslint_auto_fix: false
          prettier_auto_fix: false
          github_token: ${{ github.token }}
