# DONOT touch this file if you don't know what you are doing! TODO add codeowners file?

name: Run Tests

# Controls when the workflow will run
on:
  # Triggers the tests on creating a pull request for main branch
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: test
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 16.x

      - name: Setup Yarn
        uses: mskelton/setup-yarn@v1.0.1
        with:
          node-version: 16.x

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
          auto_fix: false
          eslint_auto_fix: false
          prettier_auto_fix: false

      # Runs a single command using the runners shell
      - name: Install all packages
        run: |
          yarn install
          echo [SUCCESS] yarn install succeeded.

      # Run all tests first to prevent broken builds
      - name: Run tests
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: |
          yarn run test
          echo [SUCCESS] tests successfully passed
