name: _Run E2E Tests

on:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  e2e_test:
    runs-on: ubuntu-latest
    name: Run E2E Tests
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Restore environment from cache
        id: restore-environment
        uses: actions/cache@v3
        env:
          cache-name: ${{ github.run_number }}
        with:
          path: ./
          key: ${{ runner.os }}-build-${{ github.run_number }}-${{ hashFiles('**/yarn.lock') }}

      - name: E2E tests
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: yarn test:e2e
