name: _Environment Setup

# Controls when the workflow will run
on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Yarn
        uses: mskelton/setup-yarn@v1
        with:
          node-version: 16.x

      - name: Install all packages
        run: |
          yarn install
          echo [SUCCESS] yarn installed

      - name: Generate prisma artifacts
        run: |
          yarn prisma-generate
          echo [SUCCESS] Prisma artifacts generated

      - name: Cache environment
        id: cache-environment
        uses: actions/cache@v3
        env:
          cache-name: ${{ github.run_number }}
        with:
          path: ./
          key: ${{ runner.os }}-build-${{ github.run_number }}-${{ hashFiles('**/yarn.lock') }}
