name: _Environment Setup

# Controls when the workflow will run
on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: c-hive/gha-yarn-cache@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Setup Yarn
        uses: mskelton/setup-yarn@v1.0.1
        with:
          node-version: 16.x

      - name: Install all packages
        run: |
          yarn install
          echo [SUCCESS] yarn installed

      - name: Generate prisma artifacts
        run: |
          yarn prisma-generate
          echo [SUCCESS] Prisma artifacts generated

      - name: Cache environment
        id: cache-environment
        uses: actions/cache@v3
        env:
          cache-name: ${{ github.run_number }}
        with:
          path: ./
          key: ${{ runner.os }}-build-${{ github.run_number }}-${{ hashFiles('**/yarn.lock') }}
