name: Sonar
on:
  push:
    branches:
      - main
    pull_request:
      types: [opened, synchronize, reopened]

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 16.x

      - name: Setup Yarn
        uses: mskelton/setup-yarn@v1.0.1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install

      - name: Test and coverage
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: yarn jest --verbose --silent --coverage --runInBand

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
      - name: SonarQube Quality Gate Check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
